In [2]:
%load_ext autoreload
%autoreload 2
%load_ext dotenv
%dotenv

In [3]:
from dotenv import load_dotenv, find_dotenv
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
import os
from llama_index.embeddings.openai import OpenAIEmbedding

# Load environment variables
load_dotenv(find_dotenv())  
embed_model = OpenAIEmbedding(model_name = os.environ.get("EMBED_MODEL"))

if embed_model is None:
    raise ValueError("EMBED_MODEL environment variable is not set!")

# Load documents
documents = SimpleDirectoryReader(input_files=["../data/Pmg_lds.md"]).load_data()

In [4]:
# merge into a single large document rather than the one document per page

from llama_index.core import Document

document = Document(text="\n\n".join([doc.text for doc in documents]))

In [5]:
from llama_index.core.node_parser import HierarchicalNodeParser

node_parser = HierarchicalNodeParser.from_defaults(chunk_sizes=[2048, 512, 128])

In [6]:
nodes = node_parser.get_nodes_from_documents([document])

In [7]:
len(nodes)

1671

In [8]:
nodes[30].text

'Activity: Personal or Companion Study (Page 110)\nStudy the following table. Think of times when you have experienced any of the feelings, thoughts, or impressions described in the passages below. As you study and gain experience, add other passages to this list. Think of how you can use these principles to help others feel and recognize the Spirit.\n\n| Scriptures | Principles\n| --- | --- |\n| D&C 6:23; 11:12-14; Romans 15:13; Galatians 5:22-23 | Gives feelings of love, joy, peace, patience, meekness, gentleness, faith, and hope. |\n| D&C 8:2-3 | Gives ideas in the mind, feelings in the heart. |\n| D&C 128:1 | Occupies the mind and presses on the feelings. |\n| Joseph Smith—History 1:11-12 | Helps scriptures have strong effect. |\n| D&C 9:8-9 | Gives good feelings to teach if something is true. | |\n| Alma 32:28; D&C 6:14-15; 1 Corinthians 2:9-11 | Enlightens the mind. |\n| Alma 19:6 | Replaces darkness with light. |\n| Mosiah 5:2-5 | Strengthens the desire to avoid evil and obey the commandments. | |\n| John 14:26 | Teaches truth and brings it to remembrance |\n| John 14:27 | Gives feelings of peace and comfort. |\n| John 16:13 | Guides to truth and shows things to come. |\n| Moroni 10:5 | Reveals truth. |\n| D&C 45:57 | Guides and protects from deception. |\n| 2 Nephi 31:18; D&C 20:27; John 16:14 | Glorifies and bears record of God the Father and Jesus Christ. |\n| D&C 42:16; 84:85; 100:5-8; Luke 12:11-12 | Guides the words of humble teachers. |\n| John 16:8 | Recognizes and corrects sin. |\n| Moroni 10:8-17; D&C 46:8-26; 1 Corinthians 12 | Gives gifts of the Spirit. |\n| Alma 10:17; 12:3; 18:16, 20, 32, 35; D&C 63:41 | Helps to perceive or discern the thoughts of others. |\n| D&C 46:30; 50:29-30 | Tells what to pray for. |\n| 2 Nephi 32:1-5; D&C 28:15 | Tells what to do. |\n| 1 Nephi 10:22; Aima 18:35 | Helps the righteous speak with power and authority. |\n| D&C 21:9; 100:8; John 15:26 | Testifies of the truth. |\n| 2 Nephi 31:17; Alma 13:12; 3 Nephi 27:20 | Sanctifies and brings remission of sins. |\n| 1 Nephi 2:16-17; 2 Nephi 33:1; Aima 24:8 | Carries truth to the heart of the listener. |\n| 1 Nephi 1:1-3; Exodus 31:3-5 | Enhances skills and abilities. |\n| 1 Nephi 7:15; 2 Nephi 28:1; 32.7; Alma 14:11; Mormon 3:16; Ether 12:2 | Constrains (impels forward) or restrains (holds back). |\n| D&C 50:13-22 | Edifies both teacher and students. |\n| D&C 88:3; John 14:26 | Gives comfort. |\n\n\n\n\nRelying on the Spirit (Page 111)\nAs the Lord’s servant, you are to do His work in His way and by His power. Some missionaries feel confident that they know how to be successful. Others lack such confidence. Remember, however, that your confidence and faith should be in Christ, not in yourself. Rely on the Spirit rather than your own talents and abilities. Trust the Spirit to guide you in every aspect of your work. The Prophet Joseph Smith taught that the Spirit is basic to teaching and preaching:\n“No man can preach the Gospel without the Holy Ghost” (History of the Church, 2:477). “Some few were called and ordained by the Spirit of revelation and prophecy, and began to preach as the Spirit gave them utterance, and though weak, yet were they strengthened by the power of God” (History of the Church, 4:538).\n“[Joseph Smith] proceeded to give instruction to the Elders respecting preaching the Gospel, and pressed upon them the necessity of getting the Spirit, so that they might preach with the Holy Ghost sent down from heaven” (History of the Church, 4:13).\nDuring your weekly and daily planning sessions, you will need to ask some basic questions every day—even many times each day (see the Scripture Study box that follows for examples of questions). Seek inspiration to answer these questions in a way that meets each situation. The answers should then take shape in your plans. But you should also be willing to follow the Spirit and change your plans when unforeseen opportunities arise.\nStudy the following scriptures and consider how they answer these important questions that you should ask each day. Consider what these passages mean for your finding efforts, planning sessions, and personal and companion study. Also consider their meaning as you teach the lessons, invite people to make commitments, follow up on commitments, strengthen new members and less-active members, and work with members.\n\n\n\n\nScripture Study (page 112)\n - Where should I go?\n  - Helaman 10:17, D&C 31:11\n  - D&C 75:26–27, D&C 79:1–2\n\n- What should I do?\n  - 1 Nephi 4:6, 2 Nephi 32:2–5\n  - D&C 28:15, D&C 52:3–4\n\n\n- What should I say?\n  - 2 Nephi 33:1, Alma 5:43–46, Alma 11:22, Helaman 5:18, Helaman 13:3–5\n  - D&C 33:8–10, D&C 50:13–22, D&C 68:1–4, D&C 75:3–11, D&C 100:5–8\n  - Matthew 10:19–20, Mark 13:11, 1 Corinthians 2:4–5...12–13, Exodus 4:10–12\n\n- How do I adapt my teaching to the needs of my investigators?\n  - Alma 12:7, Alma 41:1\n  - 3 Nephi 17:2–3, D&C 71:1, D&C 84:85\n\n- Which scriptures should I use and how should I use them?\n  - Mosiah 18:19-20, D&C 32:4, D&C 71:1 \n  - Mosiah 27:35, D&C 42:11-17, D&C 80:4 \n  = D&C 18:32-36, D&C 68:1-4, Luke 24:13-32'

In [9]:
from llama_index.core.node_parser import get_leaf_nodes

leaf_nodes = get_leaf_nodes(nodes)
print(leaf_nodes[30].text)

They want to feel secure in a world of changing values. They want “peace in this world, and eternal life in the world to come” (D&C 59:23), but they are “kept from the truth because they know not where to find it” (D&C 123:12).
The gospel of Jesus Christ as restored through the Prophet Joseph Smith will bless their families, meet their spiritual needs, and help them fulfill their deepest desires. Although they may not know why, they need relief from feelings of guilt that come from mistakes and sins.

In [10]:
nodes_by_id = {node.node_id: node for node in nodes}

parent_node = nodes_by_id[leaf_nodes[30].parent_node.node_id]
print(parent_node.text)

Consider This (Page 15)

- What is my purpose as a missionary?
- What is the gospel?
- Why do we preach the gospel?
- Why must I teach with power and authority?
- What is the message of the Restoration? Why is it so important?
- What is my responsibility in helping others become converted?
- How will I know whether I am a successful missionary?

> Questions to help study this chapter by looking for the answers





Your Commission to Teach the Restored Gospel of Jesus Christ (Page 15)

You are surrounded by people. You pass them on the street, visit them in their homes, and travel among them. All of them are children of God, your brothers and sisters. God loves them just as He loves you. Many of these people are searching for purpose in life. They are concerned for their families. They need the sense of belonging that comes from the knowledge that they are children of God, members of His eternal family. They want to feel secure in a world of changing values. They want “peace in this world, and eternal life in the world to come” (D&C 59:23), but they are “kept from the truth because they know not where to find it” (D&C 123:12).
The gospel of Jesus Christ as restored through the Prophet Joseph Smith will bless their families, meet their spiritual needs, and help them fulfill their deepest desires. Although they may not know why, they need relief from feelings of guilt that come from mistakes and sins. They need to experience the joy of redemption by receiving forgiveness of their sins and enjoying the gift of the Holy Ghost.

As an authorized representative of Jesus Christ, you can teach people with power and authority that “redemption cometh in and through the Holy Messiah,” and that no one “can dwell in the presence of God, save it be through the merits, and mercy, and grace of the Holy Messiah” (2 Nephi 2:6, 8). As people come to accept the restored gospel of Jesus Christ and receive the ordinances of baptism and confirmation by priesthood authority, they can be assured that they “are not cast off forever” (Book of Mormon, Title Page).

As your understanding of the Atonement of Jesus Christ grows, your desire to share the gospel will increase. You will feel, as Lehi did, the “great . . .

In [52]:
from llama_index.llms.openai import OpenAI

# llm = OpenAI(model ="gpt-3.5-turbo", temperature=0.1)
llm = OpenAI(model="gpt-4o-mini", temperature=0)

In [53]:
from llama_index.core import Settings

Settings.llm = llm
Settings.embed_model=embed_model
# Settings.embed_model = OpenAIEmbedding(model="text-embedding-3-small")
Settings.node_parser = node_parser

In [54]:
from llama_index.core import VectorStoreIndex, StorageContext
from llama_index.core import load_index_from_storage

if not os.path.exists("../VectorStore"):
    os.makedirs("../VectorStore")
    storage_context = StorageContext.from_defaults()
    storage_context.docstore.add_documents(nodes)

    automerging_index = VectorStoreIndex(
        leaf_nodes, storage_context=storage_context)

    automerging_index.storage_context.persist(persist_dir="../VectorStore")

else:
    automerging_index = load_index_from_storage(StorageContext.from_defaults(persist_dir="../VectorStore"))

In [55]:
from llama_index.postprocessor.cohere_rerank import CohereRerank
load_dotenv(find_dotenv())
cohere_rerank = CohereRerank(
    api_key=os.environ["COHERE_API_KEY"], 
    top_n=6,
)

In [56]:
from llama_index.core.retrievers import AutoMergingRetriever
from llama_index.core.query_engine import RetrieverQueryEngine

automerging_retriever = automerging_index.as_retriever(similarity_top_k=12)

retriever = AutoMergingRetriever(
    automerging_retriever,
    automerging_index.storage_context,
    verbose= True
)

auto_merging_engine = RetrieverQueryEngine.from_args(
    retriever, node_postprocessors=[cohere_rerank]
)

#### 4o-mini

In [57]:
response = auto_merging_engine.query("suggest some bullets points I can use to begin teaching when I eventually find somebody to teach?")

In [58]:
print(response)

- Start your first visit in a warm, respectful, and genuine manner to build trust.
- Ask simple questions about their religious background and expectations, such as, “What role has religion played in your life?”
- Encourage everyone present to join in the lesson and minimize distractions by turning off the television.
- Offer to begin and end each lesson with a prayer, asking for blessings and for them to feel the truth of your teachings.
- Quickly refer to the Restoration of the gospel, highlighting its significance as your unique message.
- Work with local leaders to identify individuals who may be open to your message, such as those who have recently experienced significant life events.
- Look for opportunities to provide simple acts of service to build connections.
- Make brief, daily visits to support and help those you are teaching, explaining your purpose during these visits.
- Keep detailed notes in your planner to follow up on commitments and invitations extended during lessons.
- Maintain frequent contact to check on progress, answer questions, and provide additional support or teachings.

### Evaluation

In [84]:
from trulens_eval import Tru

tru = Tru()
tru.reset_database()

In [85]:
import numpy as np
from trulens.apps.llamaindex import TruLlama
from trulens.core import Feedback
from trulens.providers.openai import OpenAI

# Initialize provider class
provider = OpenAI(model_engine="gpt-4o-mini")

# select context to be used in feedback. the location of context is app specific.

context = TruLlama.select_context(auto_merging_engine)

# Define a groundedness feedback function
f_groundedness = (
    Feedback(
        provider.groundedness_measure_with_cot_reasons, name="Groundedness"
    )
    .on(context.collect())  # collect context chunks into a list
    .on_output()
)

# Question/answer relevance between overall question and answer.
f_answer_relevance = Feedback(
    provider.relevance_with_cot_reasons, name="Answer Relevance"
).on_input_output()
# Question/statement relevance between question and each context chunk.
f_context_relevance = (
    Feedback(
        provider.context_relevance_with_cot_reasons, name="Context Relevance"
    )
    .on_input()
    .on(context)
    .aggregate(np.mean)
)

✅ In Groundedness, input source will be set to __record__.app.query.rets.source_nodes[:].node.text.collect() .
✅ In Groundedness, input statement will be set to __record__.main_output or `Select.RecordOutput` .
✅ In Answer Relevance, input prompt will be set to __record__.main_input or `Select.RecordInput` .
✅ In Answer Relevance, input response will be set to __record__.main_output or `Select.RecordOutput` .
✅ In Context Relevance, input question will be set to __record__.main_input or `Select.RecordInput` .
✅ In Context Relevance, input context will be set to __record__.app.query.rets.source_nodes[:].node.text .

In [86]:
tru_query_engine_recorder = TruLlama(
    auto_merging_engine,
    app_name="LlamaIndex_App",
    app_version="Advanced_Retriever",
    feedbacks=[f_groundedness, f_answer_relevance, f_context_relevance],
)

In [87]:
import pandas as pd

# Read the CSV file and drop the 'Unnamed: 0' column
df = pd.read_csv("../dataset_eval/20_dataset.csv").drop(columns=['Unnamed: 0'])

# Extract the first 20 questions into a list
questions = df['question'][:20].tolist()

# Print the list of questions
print(questions)

['What strategies can be used to make a message easy to understand when teaching?', 'What should teachers do with unfamiliar words to ensure their message is easy to understand?', 'What are some effective study techniques to enhance understanding and retention of material?', 'What is the purpose of using a study journal in your scripture study?', 'What is the importance of organizing and summarizing lesson plans for effective teaching?', 'What is the recommended method for highlighting key words when marking scriptures?', 'What is the significance of beginning study activities with a prayer?', 'What is the significance of the power of ordination in the context of missionary work?', 'What is the purpose of marking scriptures in relation to applying gospel teachings?', 'What is the significance of preaching the gospel according to President Lorenzo Snow?', 'What is the relationship between the Atonement and missionary work according to President Howard W. Hunter?', 'What are the blessings associated with receiving the gift of the Holy Ghost?', "How does Preach My Gospel support full-time and ward missionaries in advancing the Church's mission?", 'What methods can missionaries use in personal study to enhance their understanding of gospel principles and share insights with companions?', 'How does simplifying vocab help with understanding new concepts in teaching?', "What common perspective do Brigham Young and Joseph F. Smith have on the Church's mission to share truth?", 'How does living the restored gospel help with guilt and heart change?', 'What advice will the mission president give on adapting leadership with branch and district leaders for full-time and ward missionaries?', 'What strategies boost scripture marking and study depth?', 'What do Grant and Hunter say about sharing the gospel with diverse groups?']

In [88]:
# evaluate
for question in questions:
    with tru_query_engine_recorder as recording:
        response = auto_merging_engine.query(question)

> Merging 2 nodes into parent node.
> Parent node id: 828b8306-9ab2-4ede-9c41-eb1dafcc8aab.
> Parent node text: Search, Ponder, and Remember (Page 36)
- Be alert. Exercise, shower, and pray before you study.
-...

> Merging 3 nodes into parent node.
> Parent node id: 63b7ba91-684f-4b9b-b13f-7004075fbda2.
> Parent node text: Use Study Resources (Page 37)
- Use the study aids in the LDS edition of the scriptures (Topical ...

> Merging 3 nodes into parent node.
> Parent node id: 4a11252f-bcc1-40a8-8ff2-ff1081645219.
> Parent node text: Marking Scriptures (Page 38)

Marking your scriptures can assist you in thinking deeply about a p...

> Merging 3 nodes into parent node.
> Parent node id: 63b7ba91-684f-4b9b-b13f-7004075fbda2.
> Parent node text: Use Study Resources (Page 37)
- Use the study aids in the LDS edition of the scriptures (Topical ...

> Merging 3 nodes into parent node.
> Parent node id: 828b8306-9ab2-4ede-9c41-eb1dafcc8aab.
> Parent node text: Search, Ponder, and Remember (Page 36)
- Be alert. Exercise, shower, and pray before you study.
-...

> Merging 1 nodes into parent node.
> Parent node id: a0ea3ebd-aa2b-4849-8414-fe3420d454c7.
> Parent node text: Cultural Views of Scriptures (Page 195)
Most religions have sacred texts or books of scripture, b...

> Merging 3 nodes into parent node.
> Parent node id: 4a11252f-bcc1-40a8-8ff2-ff1081645219.
> Parent node text: Marking Scriptures (Page 38)

Marking your scriptures can assist you in thinking deeply about a p...

> Merging 1 nodes into parent node.
> Parent node id: a0ea3ebd-aa2b-4849-8414-fe3420d454c7.
> Parent node text: Cultural Views of Scriptures (Page 195)
Most religions have sacred texts or books of scripture, b...

> Merging 2 nodes into parent node.
> Parent node id: 2c2fdb3f-93d7-4034-814e-eacb155c62e5.
> Parent node text: First Presidency Message (Page 7)

Dear Fellow Missionary:

We compliment you on the great opport...

> Merging 1 nodes into parent node.
> Parent node id: 782b1a19-fbdb-4527-bdc9-75efa6fd695a.
> Parent node text: Help people gain faith in Jesus Christ unto repentance by teaching and testifying that the fulnes...

> Merging 3 nodes into parent node.
> Parent node id: 42e7f963-868e-4eb1-b544-2976477a7b0c.
> Parent node text: > Lesson Three: Fifth Principle



The Gift of the Holy Ghost (Page 79)
Jesus taught that we must...

> Merging 2 nodes into parent node.
> Parent node id: 2c2fdb3f-93d7-4034-814e-eacb155c62e5.
> Parent node text: First Presidency Message (Page 7)

Dear Fellow Missionary:

We compliment you on the great opport...

> Merging 1 nodes into parent node.
> Parent node id: 5f4e2962-8905-42c4-9d29-6f0295e8c11e.
> Parent node text: God answers your prayers through personal inspiration and revelation. Through the Holy Ghost He w...

> Merging 3 nodes into parent node.
> Parent node id: 4a11252f-bcc1-40a8-8ff2-ff1081645219.
> Parent node text: Marking Scriptures (Page 38)

Marking your scriptures can assist you in thinking deeply about a p...

> Merging 2 nodes into parent node.
> Parent node id: 828b8306-9ab2-4ede-9c41-eb1dafcc8aab.
> Parent node text: Search, Ponder, and Remember (Page 36)
- Be alert. Exercise, shower, and pray before you study.
-...

In [89]:
records, feedback = tru.get_records_and_feedback(app_ids=[])
# records.head()

In [90]:
import pandas as pd

pd.set_option("display.max_colwidth", None)
records[["input", "output"] + feedback]

,input,output,Context Relevance,Answer Relevance,Groundedness
0,"""What strategies can be used to make a message easy to understand when teaching?""","""To make a message easy to understand when teaching, consider the following strategies:\n\n1. **Define Unfamiliar Words**: Identify and explain any words or phrases that may be unfamiliar to your audience. Use simple definitions and refer to resources like the Bible Dictionary and True to the Faith for clarity.\n\n2. **Engage with Questions**: Ask your audience questions to gauge their understanding, such as, \u201cDo you know what we mean when we say...?\u201d This encourages interaction and helps clarify any confusion.\n\n3. **Observe Nonverbal Communication**: Pay attention to body language, facial expressions, and tone of voice, both yours and that of your audience. This can provide insights into their feelings and understanding.\n\n4. **Use Concise Statements**: Be prepared to present your message in a brief and impactful manner. Aim for short, powerful statements that convey the core message effectively.\n\n5. **Revisit Previous Lessons**: If necessary, return to earlier lessons to reinforce and clarify important doctrines, ensuring that your audience has a solid understanding.\n\nBy implementing these strategies, you can enhance comprehension and facilitate a more effective teaching experience.""",0.777778,1.0,0.666667
1,"""What should teachers do with unfamiliar words to ensure their message is easy to understand?""","""Teachers should take the time to define unfamiliar words and principles clearly. They can prepare by studying key definitions and terms, using resources like the Bible Dictionary and True to the Faith. It's important to explain these words simply and to check for understanding by asking questions. Teachers should also be attentive to whether a word or principle is new to their audience and be willing to revisit previous lessons to clarify any difficult concepts. Writing definitions in a study journal and sharing them with others can help refine their explanations. Ultimately, the goal is to ensure that both the teacher and the learners are edified and can rejoice together in their understanding.""",0.944444,1.0,1.000000
2,"""What are some effective study techniques to enhance understanding and retention of material?""","""To enhance understanding and retention of material, consider the following techniques:\n\n1. Begin with prayer to seek understanding.\n2. Study in a focused environment, such as at a desk or table, to remain alert.\n3. Organize your study materials and write notes to reinforce learning.\n4. Study by topic and ask reflective questions about the material.\n5. Visualize concepts to create a mental image of what you are learning.\n6. Engage with the words of living prophets and utilize approved resources.\n7. Keep a study journal to record questions and insights, and seek answers through scriptures and other resources.\n8. Mark your scriptures and take notes in the margins to clarify ideas.\n9. Share your learnings with others, as teaching can deepen your understanding.\n10. Memorize key passages that support the principles you are studying.\n11. Use new vocabulary in sentences and practice pronunciation to reinforce learning.\n12. Regularly review and revisit material to strengthen retention.""",0.611111,1.0,0.486111
3,"""What is the purpose of using a study journal in your scripture study?""","""The purpose of using a study journal in scripture study is to help understand, clarify, and remember what is being learned. It serves as a tool to record thoughts and impressions, allowing for the recall of spiritual experiences, recognition of growth, and the ability to access key information in the future. Additionally, it enhances the likelihood of receiving further insights and light, making it a valuable resource for personal and companion study, as well as for teaching and applying learned principles.""",0.722222,1.0,1.000000
4,"""What is the importance of organizing and summarizing lesson plans for effective teaching?""","""Organizing and summarizing lesson plans is crucial for effective teaching as it helps to present the doctrine clearly and with spiritual power. A well-structured lesson plan allows the teacher to focus on key elements such as doctrine, baptismal interview questions, and commitments, while also incorporating relevant scriptures, questions, and examples. This preparation ensures that the teaching is tailored to the needs of the investigators, facilitating their growth in faith, repentance, and readiness for baptism and confirmation. Additionally, refining lesson plans over time enhances the teaching process, making it more effective and impactful for those being taught.""",0.444444,1.0,1.000000
5,"""What is the recommended method for highlighting key words when marking scriptures?""","""The recommended method for highlighting key words when marking scriptures includes circling or underlining the key words and then using straight lines to link closely related words. This approach helps to visually connect important concepts within the text.""",0.666667,1.0,1.000000
6,"""What is the significance of beginning study activities with a prayer?""","""Beginning study activities with a prayer is significant because it invites the Holy Ghost to assist in the learning process, fostering an environment conducive to spiritual growth and understanding. Prayer serves as an act of faith, allowing individuals to seek guidance and inspiration, which can enhance their ability to teach and connect with others. It also helps to focus the mind and heart on the purpose of the study, ensuring that the time spent is productive and aligned with the needs of those being taught. Ultimately, starting with prayer lays a foundation for meaningful learning experiences and personal growth.""",0.833333,1.0,0.888889
7,"""What is the significance of the power of ordination in the context of missionary work?""","""The power of ordination is significant in missionary work as it grants individuals the authority to preach the gospel and administer sacred ordinances. This authority is essential for fulfilling the mission of inviting others to come unto Christ through repentance, baptism, and confirmation. It emphasizes the importance of serving others and building up the Church, as well as the necessity of performing ordinances of salvation. When used worthily, this priesthood power manifests the presence of God, enabling missionaries to effectively share the gospel and help others understand the sacred nature of these ordinances. Ultimately, it plays a crucial role in the gathering of souls and the joy experienced by those who share the gospel.""",0.666667,1.0,1.000000
8,"""What is the purpose of marking scriptures in relation to applying gospel teachings?""","""Marking scriptures serves to enhance understanding and application of gospel teachings. It encourages deeper contemplation of passages and doctrines, helping individuals focus on how to apply what they learn in their lives and in teaching others. By developing a consistent marking approach, one can effectively highlight key concepts and facilitate a more meaningful study experience, ultimately strengthening their faith and ability to share the gospel.""",0.833333,1.0,0.888889
9,"""What is the significance of preaching the gospel according to President Lorenzo Snow?""","""Preaching the gospel is of utmost importance as it aligns with the divine mission entrusted to missionaries. According to President Lorenzo Snow, the Lord has a profound interest in the success of those who preach the gospel, emphasizing that this work is not only a calling but also a sacred responsibility to help bring the Lord's children closer to Him. The act of preaching is seen as a vital contribution to the Lord's work, highlighting the spiritual significance and the blessings that come from serving in this capacity.""",0.777778,1.0,1.000000
10,"""What is the relationship between the Atonement and missionary work according to President Howard W. Hunter?""","""The relationship between the Atonement and missionary work, as expressed by President Howard W. Hunter, emphasizes that experiencing the blessings of the Atonement fosters a genuine concern for the welfare of others. A significant indicator of personal conversion is the desire to share the gospel with others, highlighting that the Atonement inspires missionaries to invite and help others partake in the gospel's blessings.""",0.555556,1.0,1.000000
11,"""What are the blessings associated with receiving the gift of the Holy Ghost?""","""Receiving the gift of the Holy Ghost brings several blessings, including the constant companionship of the Holy Ghost, which provides spiritual strength and guidance throughout life. It helps individuals recognize truth, experience feelings of peace, joy, and love, and inspires a desire to serve and do good for others. The Holy Ghost also offers comfort during trials, warns of dangers, and has a cleansing and sanctifying effect. Additionally, it serves as a means to feel God's love and direction, providing a foretaste of eternal joy and a promise of eternal life.""",0.833333,1.0,1.000000
12,"""How does Preach My Gospel support full-time and ward missionaries in advancing the Church's mission?""","""Preach My Gospel provides essential principles and doctrines that are beneficial for both full-time and ward missionaries as they work to advance the Church's mission. It encourages frequent study of the manual, which helps ward missionaries and leaders fulfill their responsibilities effectively and fosters unity with full-time missionaries. The manual outlines the importance of coordination between full-time missionaries and ward members, emphasizing collaborative efforts in finding, teaching, and supporting individuals and families. \n\nAdditionally, it highlights the role of the bishop and the ward council in overseeing the progress of investigators, ensuring that the work of proclaiming the gospel is strengthened through teamwork. By following the guidance in the manual, missionaries are encouraged to seek inspiration, study the scriptures, and apply what they learn, which ultimately leads to more effective missionary work and the successful integration of new members into the Church.""",0.666667,1.0,1.000000
13,"""What methods can missionaries use in personal study to enhance their understanding of gospel principles and share insights with companions?""","""Missionaries can enhance their understanding of gospel principles in personal study by employing various methods. They should focus on reading from the standard works and approved missionary library materials, such as the Book of Mormon and other scriptures, as well as studying the doctrines of the missionary lessons and relevant chapters from Preach My Gospel. \n\nTo deepen their learning, missionaries can pray for understanding and record their insights in a study journal. This journal can serve as a reference for frequent questions and answers. Additionally, teaching the lesson to companions or other missionaries is a powerful way to reinforce their knowledge and improve their teaching abilities. \n\nMissionaries can also prepare short talks on specific questions and share them with companions or during district meetings. Engaging with recent converts to learn about their experiences can provide valuable insights into faith and conversion, which can be shared with companions to enhance collective understanding.""",0.944444,1.0,0.777778
14,"""How does simplifying vocab help with understanding new concepts in teaching?""","""Simplifying vocabulary aids in understanding new concepts by making the message more accessible to those who may not be familiar with specific terms or phrases. When complex or specialized language is broken down into simpler, more relatable terms, it allows learners to grasp the underlying principles without being hindered by confusion over vocabulary. This approach encourages engagement and facilitates a clearer communication of ideas, ensuring that both the teacher and the learner can connect and share in the learning experience. By defining unfamiliar words and concepts, teachers can create an environment where everyone feels comfortable asking questions and seeking clarification, ultimately leading to a deeper understanding of the material being taught.""",0.666667,1.0,1.000000
15,"""What common perspective do Brigham Young and Joseph F. Smith have on the Church's mission to share truth?""","""Both Brigham Young and Joseph F. Smith emphasize the importance of every individual in the Church being on a mission to share truth and promote righteousness. They believe that this mission is a lifelong responsibility for all members, encouraging them to teach principles of truth and bear testimony of the gospel. Their perspectives highlight the collective duty of Church members to actively engage in spreading the teachings of the gospel and to support one another in this endeavor.""",0.388889,1.0,1.000000
16,"""How does living the restored gospel help with guilt and heart change?""","""Living the restored gospel facilitates a profound transformation in individuals by providing a pathway to forgiveness and spiritual renewal. Through the principles of faith, repentance, and the ordinances of baptism and confirmation, individuals can experience relief from guilt and shame. The Atonement of Jesus Christ plays a crucial role in this process, allowing individuals to be cleansed of their sins and become worthy to return to the presence of God. As one grows in understanding of the Atonement, the desire to share the gospel and help others experience similar changes also increases. This journey not only alleviates burdens but also fosters a deeper connection with Heavenly Father and Jesus Christ, leading to lasting heart change.""",0.666667,1.0,0.916667
17,"""What advice will the mission president give on adapting leadership with branch and district leaders for full-time and ward missionaries?""","""The mission president will provide guidance on how to effectively collaborate with branch and district leaders, ensuring that full-time missionaries and ward missionaries work together in harmony. This may include specific instructions on adjustments needed when engaging with local leaders, emphasizing the importance of coordination in teaching and supporting investigators. The mission president will also encourage regular communication and collaboration to enhance the overall missionary efforts within the branches and districts.""",0.666667,1.0,0.777778
18,"""What strategies boost scripture marking and study depth?""","""To enhance scripture marking and deepen study, consider the following strategies:\n\n1. Utilize pencils or colored markers for marking, avoiding pens that may bleed through the pages.\n2. Employ various marking techniques such as shading, underlining, bracketing, or outlining key verses or groups of verses.\n3. Limit excessive markings to maintain clarity and understanding of your notes.\n4. Focus on underlining only a few key words to emphasize important sections.\n5. Circle or underline significant words and connect related terms with straight lines.\n6. Number related points in the margin or text for better organization.\n7. Use footnotes as a resource for deeper interpretation and understanding.\n8. Mark key verses with symbols in the margins to highlight critical passages for memory.\n\nIncorporating these methods can help you focus on applying what you learn and improve your ability to teach others effectively.""",NaN,1.0,NaN
19,"""What do Grant and Hunter say about sharing the gospel with diverse groups?""","""Both Grant and Hunter emphasize the importance of sharing the gospel with all people, regardless of their background or nationality. They highlight that taking the gospel to every kindred, tongue, and people is a significant responsibility for believers. Hunter specifically notes that this mission is a privilege in the current dispensation, underscoring the urgency and necessity of spreading the gospel universally. The teachings suggest that the gospel has the power to unite individuals from diverse races and nationalities, bringing them joy, happiness, and salvation.""",NaN,1.0,1.000000

In [91]:
tru.get_leaderboard()

,,Context Relevance,Answer Relevance,Groundedness,latency,total_cost
app_name,app_version,,,,,
LlamaIndex_App,Advanced_Retriever,0.697222,1.0,0.916435,13.35,0.000195

#### 3.5 turbo

In [42]:
response = auto_merging_engine.query("what scriptures can help me teach about faith?")

In [43]:
print(response)

1 Nephi 7:12, 2 Nephi 9:23, 2 Nephi 25:23, Moroni 7:33–34, Moroni 10:7, Alma 32, Ephesians 2:8, Ether 12, Hebrews 11, 1 Nephi 3:7, James 2:17–26, 2 Nephi 25:29, 2 Nephi 26:13, Mosiah 4:6–12, Helaman 15:7–8, and Ether 12:7–22.

In [45]:
response = auto_merging_engine.query("suggest some bullets points I can use to begin teaching when I eventually find somebody to teach?")

In [46]:
print(response)

- Begin with a warm, respectful, and genuine manner.
- Ask simple questions to understand their religious background and expectations.
- Encourage all present to join in the lesson and remove distractions.
- Start and end each lesson with a prayer.
- Refer quickly to the Restoration of the gospel.
- Offer brief, daily visits to support and help them.
- Make specific notes to follow up on commitments.
- Make frequent contact to check progress, answer questions, and provide additional teachings.

In [50]:
response = auto_merging_engine.query("How do i find people to teach?")

> Merging 3 nodes into parent node.
> Parent node id: a8db3ed9-bb96-4c70-9ad8-4a7e5ae24eaf.
> Parent node text: Activity: Companion Study (Page 180)
- Identify all the former investigators in your area book.
-...

In [51]:
print(response)

You can find people to teach by working with the bishop and ward council to identify individuals who have recently had significant life events, offering simple service opportunities, teaching members about the message of the Restoration and asking for referrals, organizing member firesides, teaching English as a second language, inviting people to Church meetings and activities, using pass-along cards and other materials, seeking referrals from various sources, coordinating with public affairs representatives for missionary service opportunities, and inviting people to baptismal services. Remember to seek the guidance of the Holy Ghost and be open to unplanned finding opportunities.